[package]
name = "parser-macros"
version = "0.0.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
syn = { version = "2.0.106", features = ["full"] }
quote = "1.0.41"
proc-macro2 = "1.0.101"

[lib]
proc-macro = true
